# Site settings ...
uri: domain.com
url: https://knockotd.github.io
name: Jeung
title: 마음이 있는 곳에 보물이 있다.
email: anjeundeun@gmail.com
author: Jeung
keywords: "Swift, Portflio, 기술블로그, 개발, developer"
description: "개발과 기술과 시행착오"
social_username: Jeung

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji
